### ISSUE TITLE
Runnings file

### ISSUE THREAD

**Issue by JackMiszencin** [bauhausjs/phantom-html2pdf#1]
Any time I try and include a path to the runnings file, I get no output. I've called convert as follows:

``` pdf.convert({'html': '/Users/jmiszencin/Projects/blah/src/public/outline_template.html', 'css': '/Users/jmiszencin/Projects/blah/src/public/css/outline.css', 'runnings': '/Users/jmiszencin/Documents/stuff.js'}, function(result){ console.log(result.getTmpPath()); }) ```

Here's what my runnings file looks like:

``` module.exports = {width: '50in', height: '9in', margin: '1px'} ```

I'm clearly doing something wrong with either the way I'm calling the function or the way I'm writing my runnings file. What can I do to fix this? Thanks in advance.

**Comment by kongou-ae** [comment]
+1

**Comment by 360disrupt** [comment]
+1
And how to handle it with coffee, should there be standing plain js I guess.
```
runnings = "module.exports = { footer: {height: '1cm', contents: function(page) { return '<footer class=\"partner\"><p>In Kooperation mit</p><img src=\"./logo.png\"/></footer>'}} }"
```
does not work for me.

**Comment by pejuam** [comment]
Did you notice my comment (and PR) on this issue at https://github.com/bauhausjs/phantom-html2pdf/issues/9?

**Comment by 360disrupt** [comment]
Yes, that is what I tried with my code above, but I didn't realize that your changes are not merged to this repo. I usually stick to the original version of the package for easier deployment with npm and to choose a specific version. 

Now I added your repo as a dependency. Does your repo update with the rest of the code? Do you know if I can install and keep a fixed version?

**Comment by terehov** [comment]
Oh no, I missed it indeed! I've been on holidays and have probably overseen that mail. Sorry for that! 
I am going to merge ist later to day and create a new npm version.

**Comment by 360disrupt** [comment]
The fix worked for me, but you have to add the style directly to the element you are adding. My css class seems to be ignored.

**Comment by lucasboleite** [comment]
Any news on when this fixed will be merged?

**Comment by dustin-H** [comment]
Is there anything to merge?

**Comment by lucasboleite** [comment]
As pejuan commented on 17 Nov 2015, he fixed this issue and a [PR](https://github.com/bauhausjs/phantom-html2pdf/pull/15) is currently opened to merge his fixes into this repo.As far as I could tell, it's waiting for documentation updates since November 2015.

**Comment by dustin-H** [comment]
Ah, ok... I know... However I had no time to write docs for this and pejuan also seems to have no time, so it got stuck. 

Sorry for that!

I just had a look again on this... It doesn't seems to be needed to write docs. 

I'm looking forward to merge and publish in the next two days. Sorry for the long waiting-time.
