### ISSUE TITLE
Can't select text in PDF

### ISSUE THREAD

**Issue by haydenbleasel** [bauhausjs/phantom-html2pdf#10]
Hey,

Your library works pretty well but I can't select the text inside the PDF, even after changing: `page.render(args.pdfPath)` to `page.render(args.pdfPath, { format: 'pdf', quality: '100' } )`

**Comment by terehov** [comment]
We've seen this behaviour on Macs only. As soon as you deploy your application on a server, which is usually a Linux or Windows machine (e.g. in a cloud) it should render a proper text inside your pdf.

**Comment by haydenbleasel** [comment]
Okay I'll test this soon and report back. If this is a known issue, should probably list it in the README.

**Comment by haydenbleasel** [comment]
@terehov Yep definitely works amazingly, although I have another issue which I'll open if it doesn't exist already (links don't work).

**Comment by terehov** [comment]
@haydenbleasel Great, thank you for your feedback. And yes, indeed, I am going to add this information to the readme.

**Comment by medikoo** [comment]
It'll be great to know, whether there is any fix for OSX for that
