### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by 360disrupt** [bauhausjs/phantom-html2pdf#13]
I managed to add background colors in the css properties but is it possible to add background images?

**Comment by JorgeAguirreLeon** [comment]
CSS properties also allow you to add background images 
Use property:
````background-image: url("your-image.jpg");```
[CSS background-images](http://www.w3schools.com/cssref/pr_background-image.asp)

**Comment by dustin-H** [comment]
Seems your problem is solved @360disrupt. Otherwise just reopen this issue.

**Comment by 360disrupt** [comment]
Can be closed.
