### ISSUE TITLE
image is not showing in pdf

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [bauhausjs/phantom-html2pdf#14]
i have given a image in html i,e <img src="xxxx:xx/.jpg"> when i convert that html to pdf image is not showing in pdf. please tell me how to get image in pdf.

**Comment by lpirola** [comment]
i got these same error. Any tips?

**Comment by SamVerschueren** [comment]
If you tried setting the delay to 2 seconds?

```js
var options = {
    paperSize: {
        delay: 2000
    }
};
```

**Comment by Amara-Balakrishna1** [comment]
not getting the image even though i have given the delay

**Comment by SamVerschueren** [comment]
My best guess is a) the path to the image is incorrect (if it's a local image) or b) the image loads very slowly (slower then 2000 ms). Have you tried an image from google images or something to test this?

**Comment by terehov** [comment]
Hey Sam, thank you so much for supporting me on this one. :-)

To avoid this problem, I usually post images as a base64 string inside the img tag.

**Comment by dustin-H** [comment]
@Amara-Balakrishna1 I close this issue as it seems solved for me. When not just reopen it!
