### ISSUE TITLE
License

### ISSUE THREAD

**Issue by philip-peterson** [bauhausjs/phantom-html2pdf#17]
Hi! I'd like to use your library, but there doesn't seem to be a LICENSE it's released under. Could you perhaps add one, pretty please?

**Comment by dustin-H** [comment]
Hi, 
sorry @philip-peterson for the late reply...

I will add the MIT License the next days.

Cheers
Dustin

**Comment by dustin-H** [comment]
#18

**Comment by philip-peterson** [comment]
Thank you!
