### ISSUE TITLE
Support multiple css and js files.

### ISSUE THREAD

**Issue by dustin-H** [bauhausjs/phantom-html2pdf#19]
Asked in #5.

Anyone wanna do this? Maybe @egrcc who asked for?

Or is this not needed?

**Comment by DrMabuse23** [comment]
any news here ?

**Comment by dustin-H** [comment]
Sorry got no time for this. Feel free to do it @DrMabuse23  ;-)

**Comment by dustin-H** [comment]
I think this isn't needed, since it would took longer to create a pdf by loading multiple files i think.
