### ISSUE TITLE
PhantomJS 2.0 support?

### ISSUE THREAD

**Issue by FezVrasta** [bauhausjs/phantom-html2pdf#2]
I'm trying the 2.0 version of PhantomJS with PhantomJS-PDF but I always get only a 0kb file.

I've downloaded the binaries of the 2.0 [from here](https://groups.google.com/forum/#!topic/phantomjs/cgTH-jqCSGg) and it works perfectly with the rasterize.js official example.

How can I use Phantom 2 with this module?

Thanks!

**Comment by dustin-H** [comment]
Hi, I heaven't tested it but why are you not downloading PhantomJS form http://phantomjs.org/ ?

**Comment by FezVrasta** [comment]
Probably because 1 year ago there wasn't an official binary :)

**Comment by dustin-H** [comment]
Yeah, okey... Sorry for the late reply.

I started maintaining this repo this week. 

Do you know if this issue still exists? I just had a look on the package.json file and saw, that the latest version of phantomjs is in the dependencies. And I know a project where it's running in production. So I think it should work with PhantomJS 2.0.

When this is solved can you close?

Cheers Dustin

**Comment by FezVrasta** [comment]
No idea sorry I never used this project after this problem.

**Comment by dustin-H** [comment]
Okey, I'm sorry for that. 

I will close this issue for now, because I think it should work. 

If somebody has similar problems later on please open a new issue.

**Comment by OrenSchwartz** [comment]
this issue reoccurs.
