### ISSUE TITLE
pdf file empty - windows

### ISSUE THREAD

**Issue by kampak1111** [bauhausjs/phantom-html2pdf#23]
Hi,

The pdf file is empty on windows. I found out the the issue is caused by a line in phantom-script.js 
`page.open(page.libraryPath + "/skeleton.html", function (status)`

It looks like the path is not correct on windows (win 8) and to get this working I used instead 
`page.open("file://" + page.libraryPath + "/skeleton.html", function (status)`
this works, but two questions:
1. Is there any way to pass in the page.libraryPath so it is parametrised
2. Could this be fixed then to work also on Windows (not sure about other platforms, as this change could potencially not work)

Thanks,
Kamil

**Comment by dustin-H** [comment]
Hi,

1. I'm not sure. I will check that this week and comment again.
2. Since the most servers are running a unix based os you better should ensure that your app will work there.

Btw.: You should think about developing on a unix based system if you want to deploy on such a system. (personal opinion)

**Comment by dustin-H** [comment]
Looks like this is an PhantomJS issue:
https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-libraryPath

The libaryPath should store the correct path. I will investigate this next week.

**Comment by SamVerschueren** [comment]
This seems to be happening on linux as well. It works on my mac though.

**Comment by dustin-H** [comment]
Ok, good to know @SamVerschueren ...

Have you tried `file://` on linux as @kampak1111 did it on windows?

**Comment by Raystorm7** [comment]
Hello, doesn't work on linux (Debian 8), the pdf is always empty.. 
There is a workaround? I need this for tomorrow :-(

**Comment by SamVerschueren** [comment]
@Raystorm7 [capture-pdf](https://github.com/SamVerschueren/capture-pdf) might be helpfull.

**Comment by Raystorm7** [comment]
@SamVerschueren you've saved my life! And my work xD
Thanks :)

**Comment by Raystorm7** [comment]
Solved by using: sudo apt-get install libfontconfig.

**Comment by dustin-H** [comment]
Seems to be solved!
