### ISSUE TITLE
Allow renderDelay to be passed in options

### ISSUE THREAD

**Issue by patgoley** [bauhausjs/phantom-html2pdf#28]
I was having trouble with larger images not loading when generating my pdf. Turns out the solution was that I just needed a longer delay before the PDF was rendered. Could we expose renderDelay as an option to the convert function so callers can control it? Happy to created the PR for this, just wanted to run it by you first. Thanks!

**Comment by dustin-H** [comment]
Sure, contribution is very welcome!

**Comment by patgoley** [comment]
@dustin-H Sorry about this, I was actually using the outdated phantomjs-pdf, but it looks like with html2pdf you can pass renderDelay in the pageSize options, so you can ignore this issue. Thanks!

**Comment by dustin-H** [comment]
Okey, thanks!
