### ISSUE TITLE
problem in Pdf generation for large set of data

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [bauhausjs/phantom-html2pdf#29]
Hi 
 I am using phantom html2pdf .for conversion of html to pdf. it is working finr for small set of data. if data be like 150 pages of pdf is there . it is not printing starting pages in pdf.  can you please tell me how to overcome this problem.

i need to have pdf of around 150 pages.

**Comment by dustin-H** [comment]
Hi,
since you have a lot of pages phantom may take a while for rendering them.
So please try to set `options.paperSize.delay` to something big like `5000`, `10000` or even more.

This is the time in milliseconds until phantom-html2pdf starts rendering the pdf file. `1000ms = 1s`

**Comment by Amara-Balakrishna1** [comment]
Hi ,
Actually my pdf contains base64 image. if i remove that image my pdf is rendering perfectly. if i keep that image and data is reduced then it is rendering with image . is there a way to solve that ?

**Comment by dustin-H** [comment]
Maybe this is to big? I think this is a phantomjs issue not one of this lib.
