### ISSUE TITLE
How can I add a background page?

### ISSUE THREAD

**Issue by RodolfoSilva** [bauhausjs/phantom-html2pdf#32]
I need add one background for all pages like:
<img src="http://www.estudio2002.com/imgs/trabalhos/PapelCartaA.jpg">
<img src="http://www.jmgraficaebrindes.com.br/wp-content/uploads/Papel-Timbrado_Colorido4x4_1.jpg">

How can I do that?

**Comment by dustin-H** [comment]
Sorry I don't know.

You may want to check out [this](http://stackoverflow.com/questions/21964043/can-i-force-phantomjs-to-render-pdfs-with-the-background-images-and-colors).

Sorry for the late reply!
