### ISSUE TITLE
non uniform borders

### ISSUE THREAD

**Issue by czarly** [bauhausjs/phantom-html2pdf#35]
i would like to have non uniform borders like specified in the phantoms doc

border: {left: '2cm', top: '2cm', right: '2cm', bottom: '3cm'}

currently when using a object for border dimensions it is set to default (0).

**Comment by dustin-H** [comment]
Hey @czarly,

No one will do this for you. When you want to get help please show what you tried so far.

> Hint: You can do this by configuring the [runnings file](https://github.com/bauhausjs/phantom-html2pdf#runnings-file)

I am closing this because this is no Issue! When you have a serious question with enough detail to give anyone a chance to answer you are welcome to create a new issue.
