### ISSUE TITLE
Switching dependency to include phantomjs-prebuilt?

### ISSUE THREAD

**Issue by ajmas** [bauhausjs/phantom-html2pdf#36]
Would be worth adding an optional dependency to phantomjs-prebuilt and if not satisfied looking in the system search path?

**Comment by dustin-H** [comment]
Hi @ajmas,

Sorry I don't understand your question. `phantomjs-prebuilt` is already a dependency.

Cheers Dustin

**Comment by dustin-H** [comment]
Closing because of no reaction.
