### ISSUE TITLE
using strings instead of files

### ISSUE THREAD

**Issue by mwaschkowski** [bauhausjs/phantom-html2pdf#39]
Hi,

I'm wondering if there is a way to pass in a string instead of a file for the html input?

Thank you,

Mark

**Comment by dustin-H** [comment]
Hi @mwaschkowski,

Yes this should work. See [here](https://github.com/bauhausjs/phantom-html2pdf/blob/master/test/phantom-html2pdf.test.js).

Cheers 
Dustin

**Comment by mwaschkowski** [comment]
OK, great, thanks!

Mark
