### ISSUE TITLE
3.1.0 vs 4.0.0

### ISSUE THREAD

**Issue by christianbundy** [bauhausjs/phantom-html2pdf#40]
It looks like this repo shows `package.json` as 3.1.0, but the most recent version on NPM is 4.0.0. Is there a reason for this, or was pushing v4 accidental? I'd like to stay up-to-date with the most recent version on NPM, but I'm confused at the version mismatch. Thanks for your work maintaining this product!

**Comment by dustin-H** [comment]
Hi @christianbundy,

sorry for that. Just forgot to commit `package.json` as I updated last time.

Cheers, Dustin

**Comment by christianbundy** [comment]
Thanks Dustin, really appreciate it!
