### ISSUE TITLE
It flebox working?

### ISSUE THREAD

**Issue by MOUMBE** [bauhausjs/phantom-html2pdf#43]
Flexbox style notre recognize
Anyone Can help me?

**Comment by dustin-H** [comment]
http://stackoverflow.com/questions/35497385/flex-on-phantomjs

Come on...
1. You can discover this by searching 10 seconds on Google
2. Please look at your spelling.

**Comment by MOUMBE** [comment]
Hello,
Thanks for your help!
My environnement : phantomjs (version 2.1.1)
I use flexbox in page, css style ({display:flex;}.
Screen capture of page 
![image](https://cloud.githubusercontent.com/assets/1147680/23705802/c351fe9e-040b-11e7-9c43-ee33f86eedfb.png)

And pdf render 
![image](https://cloud.githubusercontent.com/assets/1147680/23705855/00b85f76-040c-11e7-8d19-8d121f70774d.png)

Thanks!
