### ISSUE TITLE
Page break

### ISSUE THREAD

**Issue by jyyblue1987** [bauhausjs/phantom-html2pdf#45]
I have html page with long table,
when convert this html to pdf with this library, table row at page start and end is cut off.

I thank if you let me know how to avoid this issue.
[Detail_Report_By_Date_16_Jun_2017_17_13.pdf](https://github.com/bauhausjs/phantom-html2pdf/files/1080306/Detail_Report_By_Date_16_Jun_2017_17_13.pdf)

**Comment by dustin-H** [comment]
https://stackoverflow.com/questions/9288802/avoid-page-break-inside-row-of-table

http://lmgtfy.com/?q=phantomjs+pdf+page+break+table
