### ISSUE TITLE
Calling an asynchronous function without callback is deprecated - fs.close()

### ISSUE THREAD

**Issue by SimonMARTIN87** [bauhausjs/phantom-html2pdf#47]
Hi guys. Thank you for this very good package.
But using convert() in Node 7.4.x produces :

`DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:104:12)
    at Object.fs.close (fs.js:522:20)
    at .../node_modules/phantom-html2pdf/lib/phantom-html2pdf.js:131:14`

Actually, 
`fs.close(tmpFd);`

Should use fs.closeSync.

May I create a PR?

**Comment by dustin-H** [comment]
Hi @SimonMARTIN87,

thanks for reporting! PR is very welcome. I will merge it!

Cheers,
Dustin

**Comment by dustin-H** [comment]
Closed with #48
