### ISSUE TITLE
how to set multiple css file?

### ISSUE THREAD

**Issue by egrcc** [bauhausjs/phantom-html2pdf#5]
I have 2 css file need set, but I don't how to set multiple css file use options like below: 

{
    "html" : "Path to HTML file",
    "css" : "Path to additional CSS file",
    "js" : "Path to additional JavaScript file",
    "runnings" : "Path to runnings file. Check further below for explanation.",
    "deleteOnAction" : true/false (Deletes the created temp file once you access it via toBuffer() or toFile())
}

**Comment by dustin-H** [comment]
Hi, sorry for the late reply.

I just had a look on the code. Seems this isn't possible. Do you still need it?

Planning to add it in a next release.

Cheers Dustin

**Comment by dustin-H** [comment]
I created a new issue for supporting this. Any discussion please there: #19

**Comment by egrcc** [comment]
thanks for your reply. I already solved my problem by another approach.

**Comment by simonmilz** [comment]
Any updates or news here?
