### ISSUE TITLE
pdf file does not open

### ISSUE THREAD

**Issue by infFenrir** [bauhausjs/phantom-html2pdf#57]
phantom-html2pdf - 4.0.1, win10, electron 2.0.1
Hello
I read a lot of articles, but still does not work ....
When packing electron applications -> with electron-builder without asar all works,
but with the asar and the unpacked module -> app.asar.unpacked \ node_modules \ phantomjs-prebuilt
... the file is created without any errors, but when it is rejected it gives out -> the file is corrupt or it does not have the correct encoding.

**Comment by dustin-H** [comment]
I think this is not a problem with this module. 

We simply call phantomjs so your problem must be there.

**Comment by infFenrir** [comment]
Thank you for your answer, I will try to look for a problem in phantomjs ... Sorry for the time spent )
