### ISSUE TITLE
Bookmarks or table of contents

### ISSUE THREAD

**Issue by djarvis** [bauhausjs/phantom-html2pdf#59]
Is there any support for bookmarks or table of contents?

**Comment by dustin-H** [comment]
Hi @djarvis 

this is just a small wrapper around [PhantomJS](https://github.com/ariya/phantomjs). So you should have a look at PhantomJS for any features.

Maybe these links can help you:

https://github.com/ariya/phantomjs/issues/14891
https://github.com/ariya/phantomjs/issues/13959

Cheers,
Dustin
