### ISSUE TITLE
White border

### ISSUE THREAD

**Issue by daankets** [bauhausjs/phantom-html2pdf#6]
It seems as if there is no way to get rid of the white border of 1cm. I had to change the
```javascript
var paperBorder = "0cm";
```

variable in phantomjs-pdf.js in order to do this.

**Comment by befreestudios** [comment]
You should be able to set this in the "paperSize" property of the configuration object.. this worked for me.

`return {
    html: htmlData,
    css: pdfStyle,
    "paperSize": {
      format: "A4",
      orientation: "portrait",
      border: "0.5cm"
    },
    "deleteOnAction": true
  };`
