### ISSUE TITLE
what should go in the "runnings" property ?

### ISSUE THREAD

**Issue by saru95** [bauhausjs/phantom-html2pdf#9]
MY options look like this , 
```js
var options = {
		"html": "print.html",
		"paperSize": { 
			format: 'A4', 
			orientation: 'portrait', 
			border: '1cm' 
		},
		"deleteOnAction": true
	} ;
```
However, I have no idea as to what should go inside the runnings property .

**Comment by pejuam** [comment]
I did something like this to get customized header and footer:

```
var runnings = "module.exports = { header: {height: '1cm', contents: function(page) { return page === 1 ? '' : '<div style=\"text-align: center\">Title</div>' }}, footer: {height: '1cm', contents: function(page, pages) { return '<div style=\"text-align: center\">' + page + '/' + pages + '</div>'}} }"
...
"runnings" : runnings
```
However, conversion implementation seem to be buggy. I made two fixes into code before conversion was made successfully. Fixes are found here: https://github.com/pejuam/phantom-html2pdf/commits/master

**Comment by terehov** [comment]
Would you mind to update the docs as well? Thanks!

**Comment by dustin-H** [comment]
@saru95 Is this solved for you with the answer from @pejuam?

**Comment by befreestudios** [comment]
Can someone please explain what the "runnings" file does and provide an example of it? This seems to be an important item that is completely undocumented, unless I'm missing something. 

Thanks in advance.

**Comment by dustin-H** [comment]
@befreestudios https://github.com/bauhausjs/phantom-html2pdf#runnings-file

**Comment by befreestudios** [comment]
@dustin-H Not sure how I missed that.. (bows head in shame, lol)

BTW awesome little lib, nice job. Does exactly what we need with minimal configuration.

**Comment by dustin-H** [comment]
Thanks! Credits to @PhilippCh for initially creating this!
